### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by pySilver** [birjolaxew/yet-another-medium-zoom#3]
After spending **long** few hours trying alternative libraries like

* https://github.com/francoischalifour/medium-zoom
* https://github.com/kingdido999/zooming
* https://github.com/terrymun/Fluidbox

and having various issues with each of them (lack of mobile support, weird behaviour, positioning issues, weird sizing for highres image, lack of scrset support etc etc) I finally found your library.

Thank you!

**Comment by birjolaxew** [comment]
I'm glad you can use it :) If you run into any issues, please give me a shout; a fresh set of eyes usually finds a couple problems.
